services:
  - type: web
    name: pifagor-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "30"
      - key: NOTIFICATION_EMAIL
        value: pifagor.by@gmail.com
