"""add used_by_user_id to invite_codes

Revision ID: 6241aa1584ed
Revises: 6e268cdb7563
Create Date: 2026-07-01 21:40:44.924259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6241aa1584ed'
down_revision: Union[str, Sequence[str], None] = '6e268cdb7563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
