"""add used_by_user_id to invite_codes

Revision ID: 6e268cdb7563
Revises: 
Create Date: 2026-06-24 17:58:28.519214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e268cdb7563'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite_codes', sa.Column('used_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invite_codes', 'users', ['used_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite_codes', type_='foreignkey')
    op.drop_column('invite_codes', 'used_by_user_id')
    # ### end Alembic commands ###